-- Create CUSTOMER table
CREATE TABLE IF NOT EXISTS LOAN_MANAGER_USER (
    ID uuid NOT NULL PRIMARY KEY,
    EMAIL VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    TOKEN VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID uuid NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    SURNAME VARCHAR(20) NOT NULL,
    CREDIT_LIMIT DECIMAL(19, 2) NOT NULL,
    USED_CREDIT_LIMIT DECIMAL(19, 2) NOT NULL,
    USER_ID uuid NOT NULL,
    CONSTRAINT fk_customer_user FOREIGN KEY (USER_ID) REFERENCES LOAN_MANAGER_USER(ID)
);

CREATE TABLE IF NOT EXISTS LOAN (
    ID uuid NOT NULL PRIMARY KEY,
    LOAN_AMOUNT DECIMAL(19, 2) NOT NULL,
    NUMBER_OF_INSTALLMENTS DECIMAL(19, 2) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    IS_PAID BOOLEAN NOT NULL,
    CUSTOMER_ID uuid NOT NULL,
    CONSTRAINT fk_loan_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE IF NOT EXISTS LOAN_INSTALLMENT (
    ID uuid NOT NULL PRIMARY KEY,
    AMOUNT DECIMAL(19, 2) NOT NULL,
    PAID_AMOUNT DECIMAL(19, 2) NOT NULL,
    DUE_DATE DATE NOT NULL,
    PAYMENT_DATE DATE,
    IS_PAID BOOLEAN NOT NULL,
    LOAN_ID uuid NOT NULL,
    CONSTRAINT fk_loan_installment FOREIGN KEY (LOAN_ID) REFERENCES LOAN(ID)
);