INSERT INTO LOAN_MANAGER_USER (ID, EMAIL, PASSWORD, ROLE)
VALUES (RANDOM_UUID(), 'berke@test.com', '$2a$12$6iCQyZ.jlst0BjDiNl2KkefJGBxJJ7lbyZkhPkkj/.M4KibUg5V0S', 'ADMIN');

INSERT INTO CUSTOMER (ID, NAME, SURNAME, CREDIT_LIMIT, USED_CREDIT_LIMIT, USER_ID)
VALUES (RANDOM_UUID(), 'berke', 'guvenc', 1000000, 0, (SELECT ID FROM LOAN_MANAGER_USER WHERE EMAIL = 'berke@test.com'));